"""
INT8 Quantized Heuristic Neural Policy Engine.
Operates within a strict 350 KB (358,400 bytes) parameter budget.
Navigates local concept branches and proposes candidate reductions and SpectreVM verification bytecode.
Zero floating-point operations; pure integer arithmetic with deterministic activation scaling.
"""

import os
import hashlib
from dataclasses import dataclass
from typing import List, Tuple, Dict, Any, Optional
from engine.spectre_vm import Opcode, Instruction

# Strict parameter memory budget: exactly 350 KB
INT8_PARAM_COUNT = 358_400


@dataclass
class CandidateProposal:
    """A heuristic state proposal generated by the INT8 neural policy."""
    proposed_lemma: int
    confidence_score: int         # 0..100 (scaled integer)
    concept_domain: str
    verification_bytecode: List[Instruction]
    proposal_hash: str


class NeuralPolicy:
    """
    Lightweight INT8 quantized heuristic policy model.
    Weights are pre-allocated as a flat 358,400-byte contiguous array.
    """

    def __init__(self, weights: Optional[bytes] = None, seed_domain: str = "general"):
        self.seed_domain = seed_domain

        if weights is not None:
            if len(weights) != INT8_PARAM_COUNT:
                raise ValueError(f"Invalid INT8 weight size: {len(weights)} bytes. Must be exactly {INT8_PARAM_COUNT} bytes (350 KB).")
            self.weights = bytearray(weights)
        else:
            # Deterministically synthesize pseudo-random INT8 weights from domain seed
            self.weights = self._generate_seed_weights(seed_domain)

    @staticmethod
    def _generate_seed_weights(domain: str) -> bytearray:
        """Deterministically generates 358,400 INT8 weights from a domain seed."""
        out = bytearray(INT8_PARAM_COUNT)
        state = hashlib.sha256(domain.encode("utf-8")).digest()
        idx = 0
        counter = 0

        while idx < INT8_PARAM_COUNT:
            state = hashlib.sha256(state + counter.to_bytes(4, "little")).digest()
            counter += 1
            chunk_len = min(len(state), INT8_PARAM_COUNT - idx)
            out[idx:idx + chunk_len] = state[:chunk_len]
            idx += chunk_len

        return out

    def get_memory_footprint(self) -> int:
        """Returns the resident weight footprint in bytes."""
        return len(self.weights)

    def propose_candidate(
        self,
        input_vector: List[int],
        expected_invariant: str = "non_negative"
    ) -> CandidateProposal:
        """
        Runs integer-quantized forward inference over the input state vector,
        evaluates candidate branches, and generates the candidate lemma and verifier bytecode.
        """
        # Pad or slice input to 8 dimensions
        vec = [int(v) for v in (input_vector + [0] * 8)[:8]]

        # Layer 1: Dot product of first 8 weights against input
        accum = 0
        for i in range(8):
            w = self.weights[i] - 128  # Convert uint8 to signed INT8 (-128..127)
            accum += vec[i] * w

        # Heuristic confidence score (0..100)
        confidence = min(max(abs(accum) % 101, 10), 100)

        # Proposed reduction lemma (deterministic integer transformation matching invariant goal)
        if expected_invariant == "non_negative":
            proposed_lemma = abs(accum // 16) if accum != 0 else 42
        elif expected_invariant == "strictly_positive":
            proposed_lemma = abs(accum // 16) + 1
        elif expected_invariant == "conservation_of_sum":
            proposed_lemma = (accum // 16) if accum != 0 else 42
        else:
            proposed_lemma = abs(accum // 16) % 10000

        # Synthesize the corresponding SpectreVM verification bytecode
        bytecode: List[Instruction] = []

        if expected_invariant == "non_negative":
            # Invariant: proposed_lemma >= 0
            bytecode = [
                (Opcode.PUSH, proposed_lemma),
                (Opcode.DUP, 0),
                (Opcode.PUSH, 0),
                Opcode.GTE,
                Opcode.ASSERT,              # Assert proposed_lemma >= 0
                Opcode.EMIT_LEMMA,          # Emit the verified lemma
                Opcode.HALT_PASS
            ]
        elif expected_invariant == "strictly_positive":
            # Invariant: proposed_lemma > 0
            bytecode = [
                (Opcode.PUSH, proposed_lemma),
                (Opcode.DUP, 0),
                (Opcode.PUSH, 0),
                Opcode.GT,
                Opcode.ASSERT,
                Opcode.EMIT_LEMMA,
                Opcode.HALT_PASS
            ]
        elif expected_invariant == "conservation_of_sum":
            # Invariant: input_sum == (proposed_lemma + offset)
            target_sum = sum(vec)
            offset = target_sum - proposed_lemma
            bytecode = [
                (Opcode.PUSH, proposed_lemma),
                (Opcode.PUSH, offset),
                Opcode.ADD,
                (Opcode.PUSH, target_sum),
                Opcode.EQ,
                Opcode.ASSERT,
                (Opcode.PUSH, proposed_lemma),
                Opcode.EMIT_LEMMA,
                Opcode.HALT_PASS
            ]
        else:
            # Range assertion: 0 <= proposed_lemma <= 10000
            bytecode = [
                (Opcode.PUSH, proposed_lemma),
                (Opcode.PUSH, 0),
                (Opcode.PUSH, 10000),
                Opcode.ASSERT_RANGE,
                (Opcode.PUSH, proposed_lemma),
                Opcode.EMIT_LEMMA,
                Opcode.HALT_PASS
            ]

        # Canonical hash of the proposal
        prop_str = f"{self.seed_domain}::{proposed_lemma}::{confidence}::{len(bytecode)}"
        prop_hash = hashlib.sha256(prop_str.encode("utf-8")).hexdigest()

        return CandidateProposal(
            proposed_lemma=proposed_lemma,
            confidence_score=confidence,
            concept_domain=self.seed_domain,
            verification_bytecode=bytecode,
            proposal_hash=prop_hash
        )

    def mutate(self, mutation_rate: float = 0.02, entropy_seed: bytes = b"") -> "NeuralPolicy":
        """
        Creates a mutated clone for Darwinian tombstone re-minting.
        Mutates a small fraction of INT8 weights using the provided entropy.
        """
        new_weights = bytearray(self.weights)
        mutation_hash = hashlib.sha256(bytes(self.weights[:64]) + entropy_seed).digest()

        num_mutations = int(INT8_PARAM_COUNT * mutation_rate)
        for i in range(num_mutations):
            target_idx = int.from_bytes(mutation_hash[i % 32: (i % 32) + 4], "little") % INT8_PARAM_COUNT
            delta = (mutation_hash[(i + 1) % 32] % 15) - 7
            new_val = (new_weights[target_idx] + delta) % 256
            new_weights[target_idx] = new_val

        return NeuralPolicy(weights=bytes(new_weights), seed_domain=f"{self.seed_domain}_mut")

    def export_weights(self) -> bytes:
        """Exports the contiguous 350 KB byte array."""
        return bytes(self.weights)
