"""
Unit tests for the INT8 Quantized Heuristic Neural Policy Engine.
"""

import unittest
from engine.neural_policy import NeuralPolicy, INT8_PARAM_COUNT
from engine.spectre_vm import SpectreVM


class TestNeuralPolicy(unittest.TestCase):

    def setUp(self):
        self.policy = NeuralPolicy(seed_domain="cryptography")
        self.vm = SpectreVM()

    def test_exact_350kb_footprint(self):
        self.assertEqual(self.policy.get_memory_footprint(), INT8_PARAM_COUNT)
        self.assertEqual(INT8_PARAM_COUNT, 358_400)

    def test_candidate_proposal_generation(self):
        input_vector = [12, 45, 88, 3, 90, 11, 2, 7]
        proposal = self.policy.propose_candidate(input_vector, expected_invariant="non_negative")

        self.assertIsInstance(proposal.proposed_lemma, int)
        self.assertTrue(0 <= proposal.confidence_score <= 100)
        self.assertTrue(len(proposal.verification_bytecode) > 0)
        self.assertEqual(len(proposal.proposal_hash), 64)

        # The generated bytecode should execute successfully on the SpectreVM
        res = self.vm.execute(proposal.verification_bytecode)
        self.assertTrue(res.is_verified, f"Generated bytecode failed: {res.error}")

    def test_mutation_preserves_footprint(self):
        mutated = self.policy.mutate(mutation_rate=0.01, entropy_seed=b"quantum_entropy_99")
        self.assertEqual(mutated.get_memory_footprint(), INT8_PARAM_COUNT)
        # Weights should differ slightly
        self.assertNotEqual(self.policy.export_weights(), mutated.export_weights())


if __name__ == "__main__":
    unittest.main()
