from typing import Optional, Any, TYPE_CHECKING
import binascii
from transaction import Transaction # Assuming Transaction class is in transaction.py
from pqs_utils import DEFAULT_SIG_ALG, generate_pqc_keys

# To avoid circular imports, we can use TYPE_CHECKING for the Blockchain hint
if TYPE_CHECKING:
    from blockchain import Blockchain

class AINode:
    def __init__(self, blockchain_instance: 'Blockchain', node_id: str, existing_public_key: Optional[bytes] = None, existing_private_key: Optional[bytes] = None):
        self.blockchain = blockchain_instance
        self.node_id = node_id 

        if existing_public_key and existing_private_key:
            self.public_key = existing_public_key
            self.private_key = existing_private_key
        else:
            self.public_key, self.private_key = generate_pqc_keys(self.blockchain.sig_alg)
        
        self.hex_public_key = binascii.hexlify(self.public_key).decode('ascii')

    def __repr__(self) -> str:
        return f"AINode(ID: {self.node_id}, PK: {self.hex_public_key[:10]}...)"

    def register_as_validator(self, initial_reputation: Optional[float] = None) -> None:
        """Registers this AI node as a validator on the blockchain."""
        if initial_reputation is not None:
            self.blockchain.register_validator(self.public_key, self.private_key, initial_reputation)
        else:
            self.blockchain.register_validator(self.public_key, self.private_key)
        print(f"{self} registered as validator.")

    def create_and_sign_transaction(self, recipient_pk_bytes: Optional[bytes], data: Any) -> Optional[Transaction]:
        """Creates, signs, and returns a transaction."""
        transaction = Transaction(
            sender_public_key=self.public_key,
            recipient_public_key=recipient_pk_bytes,
            data=data
        )
        try:
            transaction.sign_transaction(self.private_key, self.blockchain.sig_alg)
            return transaction
        except ValueError as e:
            print(f"Error signing transaction for {self}: {e}")
            return None

    def submit_transaction(self, transaction: Transaction) -> bool:
        """Submits a signed transaction to the blockchain's pending pool."""
        if transaction and transaction.signature:
            return self.blockchain.add_transaction(transaction)
        print(f"{self} attempted to submit an unsigned or invalid transaction.")
        return False

    # --- Methods for AI-specific actions ---

    def propose_community_engagement(self, engagement_details: Any) -> bool:
        """Creates and submits a transaction for a community engagement action."""
        data = {"type": "community_engagement_proposal", "details": engagement_details, "proposer_node_id": self.node_id}
        transaction = self.create_and_sign_transaction(recipient_pk_bytes=None, data=data)
        if transaction:
            return self.submit_transaction(transaction)
        return False

    def report_node_inactivity(self, target_node_pk_hex: str, evidence_cid: str) -> bool:
        """Creates and submits a transaction reporting another node's inactivity."""
        # In a real system, evidence_cid would point to proof of inactivity.
        data = {"type": "report_inactivity", "target_node_pk_hex": target_node_pk_hex, "evidence_cid": evidence_cid, "reporter_node_id": self.node_id}
        transaction = self.create_and_sign_transaction(recipient_pk_bytes=None, data=data)
        if transaction:
            return self.submit_transaction(transaction)
        return False

    def submit_accusation(self, accused_node_pk_hex: str, evidence_cid: str, rule_violated: str) -> bool:
        """Creates and submits a 'Proof of Misbehavior' transaction."""
        # This would be the start of an adjudication case.
        # case_id would be generated by the blockchain upon accepting this transaction.
        data = {
            "type": "proof_of_misbehavior",
            "accused_node_pk_hex": accused_node_pk_hex,
            "evidence_cid": evidence_cid, # CID pointing to detailed evidence on IPFS
            "rule_violated": rule_violated,
            "accuser_node_id": self.node_id
        }
        transaction = self.create_and_sign_transaction(recipient_pk_bytes=None, data=data)
        if transaction:
            return self.submit_transaction(transaction)
        return False

    def submit_adjudication_vote(self, case_id: str, vote_is_substantiated: bool, reasoning_cid: Optional[str] = None) -> bool:
        """Creates and submits a vote for an ongoing adjudication case."""
        data = {
            "type": "adjudication_vote",
            "case_id": case_id,
            "vote_substantiated": vote_is_substantiated, 
            "reasoning_cid": reasoning_cid, # Optional CID pointing to their reasoning
            "voter_node_id": self.node_id
        }
        transaction = self.create_and_sign_transaction(recipient_pk_bytes=None, data=data)
        if transaction:
            return self.submit_transaction(transaction)
        return False

    # Placeholder for "White Rabbit Hack" reporting
    def report_white_rabbit_finding(self, finding_details_cid: str, severity: str) -> bool:
        data = {"type": "white_rabbit_finding", "details_cid": finding_details_cid, "severity": severity, "reporter_node_id": self.node_id}
        transaction = self.create_and_sign_transaction(recipient_pk_bytes=None, data=data)
        if transaction:
            return self.submit_transaction(transaction)
        return False